workflows:
  android-release:
    name: Android Release
    max_build_duration: 60
    environment:
      vars:
        GOOGLE_MAPS_API_KEY:
          value: YOUR_GOOGLE_MAPS_API_KEY
          secure: true
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
